### ISSUE TITLE
TypeError: Cannot read property 'ttl' of undefined

### ISSUE THREAD

**Issue by fotuzlab** [fourkitchens/headless-framework#2]
Followed steps in README and I am getting following error while running "gulp local"

...
root@fotuzlab:/var/www/html/headless-framework# gulp local
[18:43:39] Warning: gulp version mismatch:
[18:43:39] Global gulp is 3.9.0
[18:43:39] Local gulp is 3.8.11
[18:43:40] Using gulpfile /var/www/html/headless-framework/Gulpfile.js
[18:43:40] Starting 'local'...
[18:43:40] Starting 'build'...
[18:43:40] Starting 'clean'...
[18:43:40] Finished 'clean' after 15 ms
[18:43:40] Starting 'dust'...
[18:43:40] Starting 'compass'...
[18:43:40] Starting 'scripts'...
[18:43:40] Starting 'images'...
[18:43:40] Finished 'compass' after 19 ms
[18:43:40] Finished 'scripts' after 14 ms
[18:43:40] Finished 'images' after 13 ms
[18:43:40] Finished 'dust' after 70 ms
[18:43:40] Finished 'build' after 86 ms
[18:43:40] Starting 'server'...
[18:43:40] Finished 'server' after 1.86 ms
[18:43:40] Starting 'watch'...
[18:43:40] Finished 'watch' after 11 ms
[18:43:40] Finished 'local' after 101 ms
[gulp] [nodemon] v1.3.7
[gulp] [nodemon] to restart at any time, enter `rs`
[gulp] [nodemon] watching: _._
[gulp] [nodemon] starting `node app.js`

/var/www/html/headless-framework/lib/config.js:9
      ttl           = nconf.get('ttl') || endpoints.ttl;
                                                   ^
TypeError: Cannot read property 'ttl' of undefined
    at Object.exports.getServerConfigs (/var/www/html/headless-framework/lib/config.js:9:52)
    at Object.<anonymous> (/var/www/html/headless-framework/app.js:14:63)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
[gulp] [nodemon] app crashed - waiting for file changes before starting...
...

Also, is there more documentation available for it?

**Comment by mattgrill** [comment]
Hi @fotuzlab 

We should probably depreciate this repository. We've moved everything, and made some improvements here, https://github.com/fourkitchens/saucier.

Additionally, it appears that your `env.json` is missing the `ttl` param. 

``` json
{
  "local": {
    "environment": "local",
    "api": "this-should-be-the-path-to-your-api",
    "ttl": "this-should-be-replaced-with-your-ttl",
    "redis": {
      "server": "127.0.0.1",
      "port": 6379
    }
  }
}
```

**Comment by fotuzlab** [comment]
Thanks Matt. Let me explore saucier.
